{
 "title": "Контроль полета",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "timeFraction", "query": "30s,1m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "RPS by method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method) (irate(grpc_requests_received_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Balance Change", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Balance changes in ${timeFraction}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(zammek_balance_change_sum[${timeFraction}])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of account replenishment values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(zammek_balance_change_bucket{type=\"increase\"}[${timeFraction}])) by (le))",
     "legendFormat": "0.5q"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(zammek_balance_change_bucket{type=\"increase\"}[${timeFraction}])) by (le))",
     "legendFormat": "0.9q"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zammek_balance_change_bucket{type=\"increase\"}[${timeFraction}])) by (le))",
     "legendFormat": "0.99q"
    }
   ]
  },
  {
   "title": "Distribution of withdrawal values from the account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(zammek_balance_change_bucket{type=\"decrease\"}[${timeFraction}])) by (le))",
     "legendFormat": "0.5q"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(zammek_balance_change_bucket{type=\"decrease\"}[${timeFraction}])) by (le))",
     "legendFormat": "0.9q"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zammek_balance_change_bucket{type=\"decrease\"}[${timeFraction}])) by (le))",
     "legendFormat": "0.99q"
    }
   ]
  },
  {
   "title": "Most fraud users last hour",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(7,\n  sum by (userId) (\n    count_over_time(\n      {service=\"zammek\"} \n      | json \n      | SourceContext = \"Zammek.Services.CreditGrpcService\" \n      | Message =~ \"Suspicious decrease transaction.*\"\n      | userId != \"\" \n      [1h]\n    )\n  )\n)",
     "legendFormat": "{{$userId}}"
    }
   ]
  },
  { "title": "Credits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 35 },
   "targets": [
    { "expr": "zammek_current_loan_percent", "legendFormat": "Loan" }
   ]
  },
  {
   "title": "Current loan rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 10, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zammek_current_loan_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}